Add a missing #include to AudioDSPKernelProcessor.h
Otherwise we get this error:

FAILED: ninja -t msvc -e environment.x86 -- "D:\jenkins\workspace\libchromiumcontent-win-e87a9670d1e0\win_toolchain\VC\bin\cl.exe" /nologo /showIncludes /FC @obj\third_party\WebKit\Source\core\gen\blink\bindings\webcore_derived.V8DerivedSources08.obj.rsp /c gen\blink\bindings\V8DerivedSources08.cpp /Foobj\third_party\WebKit\Source\core\gen\blink\bindings\webcore_derived.V8DerivedSources08.obj /Fdobj\third_party\WebKit\Source\core\webcore_derived.pdb
d:\jenkins\workspace\libchromiumcontent-win-e87a9670d1e0\vendor\chromium\src\third_party\webkit\source\wtf\ownptrcommon.h(51) : error C2027: use of undefined type 'WebCore::AudioDSPKernel'
        d:\jenkins\workspace\libchromiumcontent-win-e87a9670d1e0\vendor\chromium\src\third_party\webkit\source\platform\audio\audiodspkernelprocessor.h(44) : see declaration of 'WebCore::AudioDSPKernel'
        d:\jenkins\workspace\libchromiumcontent-win-e87a9670d1e0\vendor\chromium\src\third_party\webkit\source\wtf\ownptrcommon.h(49) : while compiling class template member function 'void WTF::OwnedPtrDeleter<T>::deletePtr(T *)'
        with
        [
            T=WebCore::AudioDSPKernel
        ]
        d:\jenkins\workspace\libchromiumcontent-win-e87a9670d1e0\vendor\chromium\src\third_party\webkit\source\wtf\ownptr.h(62) : see reference to class template instantiation 'WTF::OwnedPtrDeleter<T>' being compiled
        with
        [
            T=WebCore::AudioDSPKernel
        ]
        d:\jenkins\workspace\libchromiumcontent-win-e87a9670d1e0\vendor\chromium\src\third_party\webkit\source\wtf\ownptr.h(61) : while compiling class template member function 'WTF::OwnPtr<T>::~OwnPtr(void)'
        with
        [
            T=WebCore::AudioDSPKernel
        ]
        d:\jenkins\workspace\libchromiumcontent-win-e87a9670d1e0\vendor\chromium\src\third_party\webkit\source\wtf\vector.h(332) : see reference to class template instantiation 'WTF::OwnPtr<T>' being compiled
        with
        [
            T=WebCore::AudioDSPKernel
        ]
        d:\jenkins\workspace\libchromiumcontent-win-e87a9670d1e0\vendor\chromium\src\third_party\webkit\source\wtf\vector.h(330) : while compiling class template member function 'void WTF::VectorBuffer<T,inlineCapacity>::deallocateBuffer(T *)'
        with
        [
            T=WTF::OwnPtr<WebCore::AudioDSPKernel>,
            inlineCapacity=0
        ]
        d:\jenkins\workspace\libchromiumcontent-win-e87a9670d1e0\vendor\chromium\src\third_party\webkit\source\wtf\vector.h(457) : see reference to class template instantiation 'WTF::VectorBuffer<T,inlineCapacity>' being compiled
        with
        [
            T=WTF::OwnPtr<WebCore::AudioDSPKernel>,
            inlineCapacity=0
        ]
        d:\jenkins\workspace\libchromiumcontent-win-e87a9670d1e0\vendor\chromium\src\third_party\webkit\source\platform\audio\audiodspkernelprocessor.h(72) : see reference to class template instantiation 'WTF::Vector<T>' being compiled
        with
        [
            T=WTF::OwnPtr<WebCore::AudioDSPKernel>
        ]
d:\jenkins\workspace\libchromiumcontent-win-e87a9670d1e0\vendor\chromium\src\third_party\webkit\source\wtf\ownptrcommon.h(51) : error C2118: negative subscript
d:\jenkins\workspace\libchromiumcontent-win-e87a9670d1e0\vendor\chromium\src\third_party\webkit\source\wtf\ownptrcommon.h(52) : warning C4150: deletion of pointer to incomplete type 'WebCore::AudioDSPKernel'; no destructor called
        d:\jenkins\workspace\libchromiumcontent-win-e87a9670d1e0\vendor\chromium\src\third_party\webkit\source\platform\audio\audiodspkernelprocessor.h(44) : see declaration of 'WebCore::AudioDSPKernel'